// Generated by scripts/generate-surface.py; do not edit.

//! Generated Python classes, one per distinct named dimension.
//!
//! Each entry names a class after the first Aequitas alias of its
//! dimension and lists the dimension's other aliases, which Python binds
//! as further names of the same class. The grouping is read from the
//! dimension declarations and asserted at compile time by the macro.

use aequitas::systems::si::dimensions;

crate::quantity_classes! {
    Dimensionless: dimensions::Dimensionless,
    Angle: dimensions::Angle,
    Length: dimensions::Length,
    ReciprocalLength: dimensions::ReciprocalLength,
    Mass: dimensions::Mass,
    Time: dimensions::Time,
    ElectricCurrent: dimensions::ElectricCurrent,
    ElectricCharge: dimensions::ElectricCharge,
    ElectricPotential: dimensions::ElectricPotential,
    ElectricConductance: dimensions::ElectricConductance,
    ElectricalConductivity: dimensions::ElectricalConductivity,
    ElectricalImpedance: dimensions::ElectricalImpedance,
    Capacitance: dimensions::Capacitance,
    Polarizability: dimensions::Polarizability,
    ThermodynamicTemperature: dimensions::ThermodynamicTemperature,
    TemperatureDifference: dimensions::TemperatureDifference,
    ReciprocalTemperature: dimensions::ReciprocalTemperature,
    ReciprocalTemperatureSquared: dimensions::ReciprocalTemperatureSquared,
    AmountOfSubstance: dimensions::AmountOfSubstance,
    LuminousIntensity: dimensions::LuminousIntensity,
    Area: dimensions::Area,
    AreaPerMass: dimensions::AreaPerMass,
    Volume: dimensions::Volume,
    NumberDensity: dimensions::NumberDensity,
    ReciprocalVolume: dimensions::ReciprocalVolume,
    MolarConcentration: dimensions::MolarConcentration,
    ReactionRate: dimensions::ReactionRate,
    MolarFlux: dimensions::MolarFlux,
    Velocity: dimensions::Velocity,
    VelocityPerTemperature: dimensions::VelocityPerTemperature,
    Acceleration: dimensions::Acceleration,
    Frequency: dimensions::Frequency {
        ReciprocalTime: dimensions::ReciprocalTime,
    },
    ReciprocalTimeSquared: dimensions::ReciprocalTimeSquared,
    Pressure: dimensions::Pressure {
        EnergyPerVolume: dimensions::EnergyPerVolume,
    },
    Stress: dimensions::Stress,
    PressureRate: dimensions::PressureRate {
        VolumetricPowerDensity: dimensions::VolumetricPowerDensity,
    },
    Force: dimensions::Force,
    PressurePerElectricCurrent: dimensions::PressurePerElectricCurrent,
    PressurePerElectricPotential: dimensions::PressurePerElectricPotential {
        VolumeChargeDensity: dimensions::VolumeChargeDensity,
    },
    ElectricPotentialPerPressure: dimensions::ElectricPotentialPerPressure,
    LengthPerElectricPotential: dimensions::LengthPerElectricPotential,
    SurfaceChargeDensity: dimensions::SurfaceChargeDensity,
    SpringStiffness: dimensions::SpringStiffness,
    DampingCoefficient: dimensions::DampingCoefficient,
    MechanicalImpedance: dimensions::MechanicalImpedance,
    FlexuralRigidity: dimensions::FlexuralRigidity,
    PressureGradient: dimensions::PressureGradient,
    HydraulicResistance: dimensions::HydraulicResistance,
    HydraulicInertance: dimensions::HydraulicInertance,
    Compliance: dimensions::Compliance,
    QuadraticHydraulicResistance: dimensions::QuadraticHydraulicResistance,
    HydraulicConductance: dimensions::HydraulicConductance,
    Energy: dimensions::Energy,
    EnergyPerArea: dimensions::EnergyPerArea,
    SurfaceTension: dimensions::SurfaceTension,
    AbsorbedDose: dimensions::AbsorbedDose {
        SpecificEnergy: dimensions::SpecificEnergy,
    },
    AbsorbedDoseRate: dimensions::AbsorbedDoseRate {
        SpecificAbsorptionRate: dimensions::SpecificAbsorptionRate,
    },
    MolarEnergy: dimensions::MolarEnergy,
    MolarHeatCapacity: dimensions::MolarHeatCapacity,
    Power: dimensions::Power,
    HeatCapacity: dimensions::HeatCapacity,
    SpecificHeatCapacity: dimensions::SpecificHeatCapacity,
    ThermalConductivity: dimensions::ThermalConductivity,
    AreaPerTime: dimensions::AreaPerTime {
        ThermalDiffusivity: dimensions::ThermalDiffusivity,
        KinematicViscosity: dimensions::KinematicViscosity,
    },
    MassDensity: dimensions::MassDensity,
    MassDensityPerTemperature: dimensions::MassDensityPerTemperature,
    MassDensityRate: dimensions::MassDensityRate,
    DynamicViscosity: dimensions::DynamicViscosity,
    VolumetricFlowRate: dimensions::VolumetricFlowRate,
    AcousticImpedance: dimensions::AcousticImpedance,
    Intensity: dimensions::Intensity,
    VolumetricPowerDensityGradient: dimensions::VolumetricPowerDensityGradient,
    ReciprocalLengthPerTemperature: dimensions::ReciprocalLengthPerTemperature,
}
