// Generated by scripts/generate-surface.py; do not edit.

//! Generated inventory of every Aequitas quantity and its units.
//!
//! Each entry names a quantity alias, its dimension, and the unit
//! markers implementing `LinearUnit` for that dimension. Symbols,
//! scale factors and dimension exponents are read from the Rust
//! associated constants at expansion time, never copied here, so this
//! file records *which* units exist and never *what they mean*.

use aequitas::systems::si::{dimensions, units};

use crate::units::registry::Quantities;

crate::quantity_inventory! {
    dimensionless => Dimensionless, dimensions::Dimensionless {
    },
    angle => Angle, dimensions::Angle {
        Degree: units::Degree,
        Radian: units::Radian,
    },
    length => Length, dimensions::Length {
        Centimeter: units::Centimeter,
        Kilometer: units::Kilometer,
        Meter: units::Meter,
        Millimeter: units::Millimeter,
        Nanometer: units::Nanometer,
    },
    reciprocal_length => ReciprocalLength, dimensions::ReciprocalLength {
        PerCentimeter: units::PerCentimeter,
        PerMeter: units::PerMeter,
    },
    mass => Mass, dimensions::Mass {
        Gram: units::Gram,
        Kilogram: units::Kilogram,
    },
    time => Time, dimensions::Time {
        Microsecond: units::Microsecond,
        Millisecond: units::Millisecond,
        Second: units::Second,
    },
    electric_current => ElectricCurrent, dimensions::ElectricCurrent {
        Ampere: units::Ampere,
    },
    electric_charge => ElectricCharge, dimensions::ElectricCharge {
        Coulomb: units::Coulomb,
    },
    electric_potential => ElectricPotential, dimensions::ElectricPotential {
        Volt: units::Volt,
    },
    electric_conductance => ElectricConductance, dimensions::ElectricConductance {
        Siemens: units::Siemens,
    },
    electrical_conductivity => ElectricalConductivity, dimensions::ElectricalConductivity {
        SiemensPerMeter: units::SiemensPerMeter,
    },
    electrical_impedance => ElectricalImpedance, dimensions::ElectricalImpedance {
        Ohm: units::Ohm,
    },
    capacitance => Capacitance, dimensions::Capacitance {
        Farad: units::Farad,
    },
    polarizability => Polarizability, dimensions::Polarizability {
        FaradSquareMeter: units::FaradSquareMeter,
    },
    thermodynamic_temperature => ThermodynamicTemperature, dimensions::ThermodynamicTemperature {
        Kelvin: units::Kelvin,
    },
    temperature_difference => TemperatureDifference, dimensions::TemperatureDifference {
        DegreeCelsius: units::DegreeCelsius,
        DegreeFahrenheit: units::DegreeFahrenheit,
        Kelvin: units::Kelvin,
    },
    reciprocal_temperature => ReciprocalTemperature, dimensions::ReciprocalTemperature {
        PerKelvin: units::PerKelvin,
    },
    reciprocal_temperature_squared => ReciprocalTemperatureSquared, dimensions::ReciprocalTemperatureSquared {
        PerSquareKelvin: units::PerSquareKelvin,
    },
    amount_of_substance => AmountOfSubstance, dimensions::AmountOfSubstance {
        Mole: units::Mole,
    },
    luminous_intensity => LuminousIntensity, dimensions::LuminousIntensity {
        Candela: units::Candela,
    },
    area => Area, dimensions::Area {
        SquareCentimeter: units::SquareCentimeter,
        SquareMeter: units::SquareMeter,
    },
    area_per_mass => AreaPerMass, dimensions::AreaPerMass {
        SquareCentimeterPerGram: units::SquareCentimeterPerGram,
        SquareMeterPerKilogram: units::SquareMeterPerKilogram,
    },
    volume => Volume, dimensions::Volume {
        CubicMeter: units::CubicMeter,
        CubicMillimeter: units::CubicMillimeter,
    },
    number_density => NumberDensity, dimensions::NumberDensity {
        PerCubicMeter: units::PerCubicMeter,
    },
    reciprocal_volume => ReciprocalVolume, dimensions::ReciprocalVolume {
    },
    molar_concentration => MolarConcentration, dimensions::MolarConcentration {
        MicromolePerLiter: units::MicromolePerLiter,
        MolePerCubicMeter: units::MolePerCubicMeter,
        MolePerLiter: units::MolePerLiter,
    },
    reaction_rate => ReactionRate, dimensions::ReactionRate {
        MolePerCubicMeterSecond: units::MolePerCubicMeterSecond,
    },
    molar_flux => MolarFlux, dimensions::MolarFlux {
        MolePerSquareMeterSecond: units::MolePerSquareMeterSecond,
    },
    velocity => Velocity, dimensions::Velocity {
        MeterPerSecond: units::MeterPerSecond,
    },
    velocity_per_temperature => VelocityPerTemperature, dimensions::VelocityPerTemperature {
        MeterPerSecondKelvin: units::MeterPerSecondKelvin,
    },
    acceleration => Acceleration, dimensions::Acceleration {
        MeterPerSecondSquared: units::MeterPerSecondSquared,
    },
    frequency => Frequency, dimensions::Frequency {
        Hertz: units::Hertz,
        Kilohertz: units::Kilohertz,
        Megahertz: units::Megahertz,
    },
    reciprocal_time => ReciprocalTime, dimensions::ReciprocalTime {
        PerSecond: units::PerSecond,
    },
    reciprocal_time_squared => ReciprocalTimeSquared, dimensions::ReciprocalTimeSquared {
    },
    pressure => Pressure, dimensions::Pressure {
        Kilopascal: units::Kilopascal,
        Megapascal: units::Megapascal,
        Pascal: units::Pascal,
    },
    stress => Stress, dimensions::Stress {
        Kilopascal: units::Kilopascal,
        Megapascal: units::Megapascal,
        Pascal: units::Pascal,
    },
    pressure_rate => PressureRate, dimensions::PressureRate {
        PascalPerSecond: units::PascalPerSecond,
    },
    force => Force, dimensions::Force {
        Newton: units::Newton,
    },
    pressure_per_electric_current => PressurePerElectricCurrent, dimensions::PressurePerElectricCurrent {
    },
    pressure_per_electric_potential => PressurePerElectricPotential, dimensions::PressurePerElectricPotential {
        PascalPerVolt: units::PascalPerVolt,
    },
    electric_potential_per_pressure => ElectricPotentialPerPressure, dimensions::ElectricPotentialPerPressure {
        VoltPerPascal: units::VoltPerPascal,
    },
    length_per_electric_potential => LengthPerElectricPotential, dimensions::LengthPerElectricPotential {
        MeterPerVolt: units::MeterPerVolt,
    },
    surface_charge_density => SurfaceChargeDensity, dimensions::SurfaceChargeDensity {
        CoulombPerSquareMeter: units::CoulombPerSquareMeter,
    },
    volume_charge_density => VolumeChargeDensity, dimensions::VolumeChargeDensity {
        CoulombPerCubicMeter: units::CoulombPerCubicMeter,
    },
    spring_stiffness => SpringStiffness, dimensions::SpringStiffness {
        NewtonPerMeter: units::NewtonPerMeter,
    },
    damping_coefficient => DampingCoefficient, dimensions::DampingCoefficient {
        KilogramPerSecond: units::KilogramPerSecond,
    },
    mechanical_impedance => MechanicalImpedance, dimensions::MechanicalImpedance {
        KilogramPerSecond: units::KilogramPerSecond,
    },
    flexural_rigidity => FlexuralRigidity, dimensions::FlexuralRigidity {
        Joule: units::Joule,
    },
    pressure_gradient => PressureGradient, dimensions::PressureGradient {
    },
    hydraulic_resistance => HydraulicResistance, dimensions::HydraulicResistance {
    },
    hydraulic_inertance => HydraulicInertance, dimensions::HydraulicInertance {
    },
    compliance => Compliance, dimensions::Compliance {
    },
    quadratic_hydraulic_resistance => QuadraticHydraulicResistance, dimensions::QuadraticHydraulicResistance {
    },
    hydraulic_conductance => HydraulicConductance, dimensions::HydraulicConductance {
    },
    energy => Energy, dimensions::Energy {
        ElectronVolt: units::ElectronVolt,
        Joule: units::Joule,
        MegaElectronVolt: units::MegaElectronVolt,
    },
    energy_per_area => EnergyPerArea, dimensions::EnergyPerArea {
        JoulePerSquareMeter: units::JoulePerSquareMeter,
    },
    surface_tension => SurfaceTension, dimensions::SurfaceTension {
        NewtonPerMeter: units::NewtonPerMeter,
    },
    absorbed_dose => AbsorbedDose, dimensions::AbsorbedDose {
        Gray: units::Gray,
    },
    specific_energy => SpecificEnergy, dimensions::SpecificEnergy {
        JoulePerKilogram: units::JoulePerKilogram,
    },
    absorbed_dose_rate => AbsorbedDoseRate, dimensions::AbsorbedDoseRate {
        GrayPerSecond: units::GrayPerSecond,
    },
    specific_absorption_rate => SpecificAbsorptionRate, dimensions::SpecificAbsorptionRate {
        WattPerKilogram: units::WattPerKilogram,
    },
    molar_energy => MolarEnergy, dimensions::MolarEnergy {
        JoulePerMole: units::JoulePerMole,
    },
    molar_heat_capacity => MolarHeatCapacity, dimensions::MolarHeatCapacity {
        JoulePerMoleKelvin: units::JoulePerMoleKelvin,
    },
    power => Power, dimensions::Power {
        Watt: units::Watt,
    },
    heat_capacity => HeatCapacity, dimensions::HeatCapacity {
        JoulePerKelvin: units::JoulePerKelvin,
    },
    specific_heat_capacity => SpecificHeatCapacity, dimensions::SpecificHeatCapacity {
        JoulePerKilogramKelvin: units::JoulePerKilogramKelvin,
    },
    thermal_conductivity => ThermalConductivity, dimensions::ThermalConductivity {
        WattPerMeterKelvin: units::WattPerMeterKelvin,
    },
    area_per_time => AreaPerTime, dimensions::AreaPerTime {
    },
    thermal_diffusivity => ThermalDiffusivity, dimensions::ThermalDiffusivity {
        SquareMeterPerSecond: units::SquareMeterPerSecond,
    },
    mass_density => MassDensity, dimensions::MassDensity {
        GramPerCubicCentimeter: units::GramPerCubicCentimeter,
        KilogramPerCubicMeter: units::KilogramPerCubicMeter,
    },
    mass_density_per_temperature => MassDensityPerTemperature, dimensions::MassDensityPerTemperature {
        KilogramPerCubicMeterKelvin: units::KilogramPerCubicMeterKelvin,
    },
    mass_density_rate => MassDensityRate, dimensions::MassDensityRate {
        KilogramPerCubicMeterSecond: units::KilogramPerCubicMeterSecond,
    },
    dynamic_viscosity => DynamicViscosity, dimensions::DynamicViscosity {
        MillipascalSecond: units::MillipascalSecond,
        PascalSecond: units::PascalSecond,
    },
    kinematic_viscosity => KinematicViscosity, dimensions::KinematicViscosity {
    },
    volumetric_flow_rate => VolumetricFlowRate, dimensions::VolumetricFlowRate {
        CubicMeterPerSecond: units::CubicMeterPerSecond,
    },
    acoustic_impedance => AcousticImpedance, dimensions::AcousticImpedance {
        Rayl: units::Rayl,
    },
    intensity => Intensity, dimensions::Intensity {
        WattPerSquareMeter: units::WattPerSquareMeter,
    },
    volumetric_power_density => VolumetricPowerDensity, dimensions::VolumetricPowerDensity {
        WattPerCubicMeter: units::WattPerCubicMeter,
    },
    volumetric_power_density_gradient => VolumetricPowerDensityGradient, dimensions::VolumetricPowerDensityGradient {
        WattPerMeterFourth: units::WattPerMeterFourth,
    },
    energy_per_volume => EnergyPerVolume, dimensions::EnergyPerVolume {
        JoulePerCubicMeter: units::JoulePerCubicMeter,
        JoulePerMilliliter: units::JoulePerMilliliter,
    },
    reciprocal_length_per_temperature => ReciprocalLengthPerTemperature, dimensions::ReciprocalLengthPerTemperature {
        PerMeterKelvin: units::PerMeterKelvin,
    },
}
