#!/usr/bin/env python3
"""Generate the Python binding inventory from the Aequitas Rust surface.

Why this exists: the binding must expose every SI quantity and unit the law
crate defines, and a hand-maintained second list drifts the moment an ADR adds
a quantity. This script reads the inventory out of the Rust source and emits a
macro invocation; the *values* (unit symbol, scale, dimension exponents) are
never transcribed here -- the generated code references the Rust associated
constants, so `rustc` remains the source of truth for every number.

Run `generate` to write the file and `check` to fail when it is stale. CI runs
`check`, so an upstream quantity that never reached the binding is a red gate
rather than a silent gap.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

BANNER = "// Generated by scripts/generate-surface.py; do not edit."

# `\s+` rather than a literal space: rustfmt wraps the longer aliases onto a
# continuation line, and matching only the single-line form silently dropped
# five quantities on the first run.
QUANTITY_RE = re.compile(
    r"^pub type (?P<name>\w+)<T = f64> =\s+Quantity<T, dimensions::(?P<dimension>\w+)>;",
    re.MULTILINE,
)
UNIT_IMPL_RE = re.compile(
    r"impl LinearUnit<dimensions::(?P<dimension>\w+)> for (?P<unit>\w+)"
)
# Affine units are a separate contract: the same marker may be affine for one
# dimension and linear for another (a Celsius temperature and a Celsius
# difference), so they are collected apart and emitted under `affine`.
AFFINE_IMPL_RE = re.compile(
    r"impl AffineUnit<dimensions::(?P<dimension>\w+)> for (?P<unit>\w+)"
)


def repo_root(start: Path) -> Path:
    """Locate the Aequitas checkout root from this script's own location."""
    return start.resolve().parent.parent


def read(path: Path) -> str:
    """Read a source file as UTF-8.

    Explicit encoding: this repository is edited on Windows, where the default
    locale codec is cp1252 and silently fails on the non-ASCII characters in
    the unit documentation.
    """
    return path.read_text(encoding="utf-8")


def collect_quantities(root: Path) -> list[tuple[str, str]]:
    """Return `(alias, dimension)` pairs in source order."""
    source = read(root / "src" / "systems" / "si" / "quantities.rs")
    pairs = [(m["name"], m["dimension"]) for m in QUANTITY_RE.finditer(source)]
    if not pairs:
        raise SystemExit("no quantity aliases matched: the alias form changed")
    return pairs


def collect_units(root: Path) -> dict[str, list[str]]:
    """Map each dimension to the unit markers implementing it.

    A unit may implement several dimensions -- `Pascal` covers both `Pressure`
    and `Stress`, `Kelvin` both absolute temperature and a difference -- so the
    mapping is deliberately one-to-many and unit lookup downstream is scoped by
    dimension rather than keyed on the unit name alone.
    """
    units: dict[str, list[str]] = {}
    unit_dir = root / "src" / "systems" / "si" / "units"
    for path in sorted(unit_dir.rglob("*.rs")):
        for match in UNIT_IMPL_RE.finditer(read(path)):
            units.setdefault(match["dimension"], []).append(match["unit"])
    if not units:
        raise SystemExit("no LinearUnit impls matched: the impl form changed")
    for markers in units.values():
        markers.sort()
    return units


def collect_affine_units(root: Path) -> dict[str, list[str]]:
    """Map each dimension to the unit markers implementing `AffineUnit` for it.

    Unlike the linear set this may legitimately be empty, so an empty result is
    not treated as a changed impl form.
    """
    units: dict[str, list[str]] = {}
    unit_dir = root / "src" / "systems" / "si" / "units"
    for path in sorted(unit_dir.rglob("*.rs")):
        for match in AFFINE_IMPL_RE.finditer(read(path)):
            units.setdefault(match["dimension"], []).append(match["unit"])
    for markers in units.values():
        markers.sort()
    return units


def collect_dimension_types(root: Path) -> dict[str, str]:
    """Map each SI dimension alias to the type it names, alias chains resolved.

    Two quantity aliases whose dimensions name one type -- `Pressure` and
    `EnergyPerVolume` are both `Dimension<N1, P1, N2, ...>` -- are one type in
    Rust and so become one Python class. Only the grouping is read here: the
    generated inventory asserts at compile time that each alias has its
    class's dimension and that no two classes share one, so a mistake in this
    parse fails the build rather than shipping wrong stubs.
    """
    source = read(root / "src" / "systems" / "si" / "dimensions.rs")
    declared: dict[str, str] = {}
    for statement in source.split(";"):
        start = statement.find("pub type ")
        if start < 0:
            continue
        declaration = " ".join(statement[start + len("pub type ") :].split())
        name, separator, target = declaration.partition(" = ")
        if separator:
            declared[name] = target
    if not declared:
        raise SystemExit("no dimension aliases matched: the declaration form changed")

    def resolve(name: str) -> str:
        chain = [name]
        target = declared[name]
        while target in declared:
            if target in chain:
                raise SystemExit(f"dimension aliases form a cycle: {' -> '.join(chain)}")
            chain.append(target)
            target = declared[target]
        # `Dimension`'s semantic parameter defaults to `BaseSemantics`; spell it
        # out so a declaration that writes it groups with one that omits it.
        if target.startswith("Dimension<") and target.count(",") == 6:
            target = target[:-1] + ", BaseSemantics>"
        return target

    return {name: resolve(name) for name in declared}


def group_classes(
    quantities: list[tuple[str, str]], dimension_types: dict[str, str]
) -> list[tuple[str, str, list[tuple[str, str]]]]:
    """Group quantity aliases into one class per distinct dimension type.

    Returns `(class, dimension, [(alias, alias_dimension), ...])` in source
    order. The class takes its first alias's name, which is also the name
    `Quantity.quantity` reports for the dimension.
    """
    classes: dict[str, tuple[str, str, list[tuple[str, str]]]] = {}
    for alias, dimension in quantities:
        if dimension not in dimension_types:
            raise SystemExit(
                f"`{alias}` names dimension `{dimension}`, which dimensions.rs does not declare"
            )
        key = dimension_types[dimension]
        if key in classes:
            classes[key][2].append((alias, dimension))
        else:
            classes[key] = (alias, dimension, [])
    return list(classes.values())


def snake(name: str) -> str:
    """Convert a Rust type name to the snake_case Python attribute name."""
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).lower()


def render(
    quantities: list[tuple[str, str]],
    units: dict[str, list[str]],
    affine: dict[str, list[str]],
) -> str:
    """Render the macro invocation for the collected inventory."""
    lines = [
        BANNER,
        "",
        "//! Generated inventory of every Aequitas quantity and its units.",
        "//!",
        "//! Each entry names a quantity alias, its dimension, and the unit",
        "//! markers implementing `LinearUnit` for that dimension, plus any",
        "//! implementing `AffineUnit` under `affine`. Symbols, scale factors,",
        "//! offsets and dimension exponents are read from the Rust",
        "//! associated constants at expansion time, never copied here, so this",
        "//! file records *which* units exist and never *what they mean*.",
        "",
        "use aequitas::systems::si::{dimensions, units};",
        "",
        "use crate::units::registry::Quantities;",
        "",
        "crate::quantity_inventory! {",
    ]
    covered = set()
    for alias, dimension in quantities:
        markers = units.get(dimension, [])
        covered.add(dimension)
        lines.append(f"    {snake(alias)} => {alias}, dimensions::{dimension} {{")
        for marker in markers:
            lines.append(f"        {marker}: units::{marker},")
        affine_markers = affine.get(dimension, [])
        if affine_markers:
            lines.append("    } affine {")
            for marker in affine_markers:
                lines.append(f"        {marker}: units::{marker},")
        lines.append("    },")
    lines.append("}")

    orphans = sorted((set(units) | set(affine)) - covered)
    if orphans:
        raise SystemExit(
            "these dimensions carry units but no quantity alias, so the binding "
            f"could not name them: {', '.join(orphans)}"
        )
    return "\n".join(lines) + "\n"


def render_classes(classes: list[tuple[str, str, list[tuple[str, str]]]]) -> str:
    """Render the per-dimension class inventory."""
    lines = [
        BANNER,
        "",
        "//! Generated Python classes, one per distinct named dimension.",
        "//!",
        "//! Each entry names a class after the first Aequitas alias of its",
        "//! dimension and lists the dimension's other aliases, which Python binds",
        "//! as further names of the same class. The grouping is read from the",
        "//! dimension declarations and asserted at compile time by the macro.",
        "",
        "use aequitas::systems::si::dimensions;",
        "",
        "crate::quantity_classes! {",
    ]
    for name, dimension, aliases in classes:
        if not aliases:
            lines.append(f"    {name}: dimensions::{dimension},")
            continue
        lines.append(f"    {name}: dimensions::{dimension} {{")
        for alias, alias_dimension in aliases:
            lines.append(f"        {alias}: dimensions::{alias_dimension},")
        lines.append("    },")
    lines.append("}")
    return "\n".join(lines) + "\n"


EXTENSION_STUB = '''# Generated by scripts/generate-surface.py; do not edit.
"""Typed surface of the compiled extension."""

from typing import Dict, List, Optional, Tuple, Type, Union

Dimension = Tuple[Tuple[int, int, int, int, int, int, int], str]

BASE_ATTR: str
DIMENSION_ATTR: str
PROTOCOL_VERSION: int
UNITS: Dict[str, List[str]]

class Quantity:
    """A magnitude in canonical SI base units and the dimension it belongs to.

    Each named dimension is a subclass -- `Length`, `Area`, `AreaPerTime` --
    and every operation returns an instance of the class for its result's
    dimension, or `Quantity` itself when no class names it. These stubs type
    arithmetic as returning `Quantity`; dimensional compatibility is checked
    when the operation runs, so adding a length to a time raises `ValueError`.
    """

    @staticmethod
    def from_unit(value: float, unit: str, *, quantity: str) -> "Quantity": ...
    @staticmethod
    def from_base_of(value: float, quantity: str) -> "Quantity": ...
    @property
    def base(self) -> float: ...
    @property
    def dimension(self) -> Dimension: ...
    @property
    def quantity(self) -> Optional[str]: ...
    @property
    def quantities(self) -> List[str]: ...
    @property
    def is_dimensionless(self) -> bool: ...
    @property
    def __aequitas_base__(self) -> float: ...
    @property
    def __aequitas_dimension__(self) -> Dimension: ...
    def in_unit(self, unit: str) -> float: ...
    def sqrt(self) -> "Quantity": ...
    def cbrt(self) -> "Quantity": ...
    def reciprocal(self) -> "Quantity": ...
    def __add__(self, other: "Quantity") -> "Quantity": ...
    def __sub__(self, other: "Quantity") -> "Quantity": ...
    def __mul__(self, other: Union["Quantity", float]) -> "Quantity": ...
    def __rmul__(self, other: Union["Quantity", float]) -> "Quantity": ...
    def __truediv__(self, other: Union["Quantity", float]) -> "Quantity": ...
    def __rtruediv__(self, other: Union["Quantity", float]) -> "Quantity": ...
    def __pow__(self, exponent: int, modulo: None = ...) -> "Quantity": ...
    def __neg__(self) -> "Quantity": ...
    def __pos__(self) -> "Quantity": ...
    def __abs__(self) -> "Quantity": ...
    def __lt__(self, other: "Quantity") -> bool: ...
    def __le__(self, other: "Quantity") -> bool: ...
    def __gt__(self, other: "Quantity") -> bool: ...
    def __ge__(self, other: "Quantity") -> bool: ...
    def __hash__(self) -> int: ...

def quantity_names() -> List[str]: ...
def unit_symbols(quantity: str) -> List[str]: ...
def dimension_of(quantity: str) -> Dimension: ...
def base_value_of(value: object, expected: str) -> float: ...
'''


def render_extension_stub(classes: list[tuple[str, str, list[tuple[str, str]]]]) -> str:
    """Render the extension stub: the fixed surface plus one class per dimension."""
    lines = [EXTENSION_STUB.rstrip("\n"), "", "CLASSES: Dict[str, Type[Quantity]]", ""]
    for name, _dimension, aliases in classes:
        lines.append(f"class {name}(Quantity): ...")
        for alias, _alias_dimension in aliases:
            lines.append(f"{alias} = {name}")
    return "\n".join(lines) + "\n"


def render_package_stub(
    quantities: list[tuple[str, str]],
    units: dict[str, list[str]],
    affine: dict[str, list[str]],
) -> str:
    """Render the stub for the importable package surface."""
    lines = [
        "# Generated by scripts/generate-surface.py; do not edit.",
        '"""Typed surface of the `pyaequitas` package."""',
        "",
        "from typing import Dict, List, Optional",
        "",
        "from ._pyaequitas import (",
        "    BASE_ATTR as BASE_ATTR,",
        "    CLASSES as CLASSES,",
        "    DIMENSION_ATTR as DIMENSION_ATTR,",
        "    PROTOCOL_VERSION as PROTOCOL_VERSION,",
        "    UNITS as UNITS,",
        "    Dimension as Dimension,",
        "    Quantity as Quantity,",
        "    base_value_of as base_value_of,",
        "    dimension_of as dimension_of,",
        "    quantity_names as quantity_names,",
        "    unit_symbols as unit_symbols,",
        ")",
        "from ._pyaequitas import (",
        *[f"    {alias} as {alias}," for alias, _dimension in quantities],
        ")",
        "",
        "__all__: List[str]",
        "",
    ]
    for alias, dimension in quantities:
        symbols = ", ".join(units.get(dimension, [])) or "base units only"
        if affine.get(dimension):
            symbols += "; affine: " + ", ".join(affine[dimension])
        lines.append(f"# {alias}: {symbols}")
        lines.append(
            f"def {snake(alias)}(value: float, unit: Optional[str] = ...) -> {alias}: ..."
        )
    return "\n".join(lines) + "\n"


def targets(root: Path) -> dict[str, Path]:
    """Paths this generator owns."""
    crate = root / "crates" / "aequitas-python"
    package = crate / "python" / "pyaequitas"
    return {
        "inventory": crate / "src" / "units" / "inventory.rs",
        "classes": crate / "src" / "quantity" / "classes" / "inventory.rs",
        "extension_stub": package / "_pyaequitas.pyi",
        "package_stub": package / "__init__.pyi",
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("mode", choices=("generate", "check"))
    args = parser.parse_args()

    root = repo_root(Path(__file__))
    quantities = collect_quantities(root)
    units = collect_units(root)
    affine = collect_affine_units(root)
    classes = group_classes(quantities, collect_dimension_types(root))

    rendered = {
        "inventory": render(quantities, units, affine),
        "classes": render_classes(classes),
        "extension_stub": render_extension_stub(classes),
        "package_stub": render_package_stub(quantities, units, affine),
    }
    destinations = targets(root)

    stale = 0
    for key, path in destinations.items():
        relative = path.relative_to(root)
        if args.mode == "generate":
            # Text mode would translate "\n" to "\r\n" on
            # Windows and rewrite every unchanged generated file, so write
            # what the tree contains.
            path.write_text(rendered[key], encoding="utf-8", newline="\n")
            print(f"{relative}: written")
            continue
        if not path.exists():
            print(f"{relative}: missing", file=sys.stderr)
            stale += 1
        elif read(path) != rendered[key]:
            print(f"{relative}: stale", file=sys.stderr)
            stale += 1
        else:
            print(f"{relative}: current")

    if stale:
        print(
            "rerun `python scripts/generate-surface.py generate`",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
